server:
  port: 8082

spring:
  application:
    name: gateway-service

  cloud:
    config:
      discovery:
        enabled: true
        serviceId: configuration-service
    gateway:
      discovery:
        locator:
          enabled: true

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"