server:
  port: 8082

spring:
  application:
    name: gateway-service

  cloud:
    config:
      import: "optional:configserver:"
      discovery:
        enabled: true
        serviceId: configuration-service
    gateway:
      discovery:
        locator:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"